#! /bin/bash
#
# Startup Script for the COS adapter daemon
#
# chkconfig: - 31 76
# description: Starts and stops the COS adapter daemon
#

#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-sup-adapters/tags/CODAC-CORE-6.2B2/src/main/scripts/sup-adapter-d1-j4-fir $
# $Id: sup-adapter-d1-j4-fir 96477 2019-01-09 14:53:55Z sivecm $
#
# Project       : CODAC Core System
#
# Description   : Startup Script for the COS adapter daemon
#
# Author(s)     : Kevin Meyer (Cosylab)
#
# Copyright (c) : 2010-2019 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

. codacenv

#REQUSER="root"
unset REQUSER

###########################################################################################


# DAEMONS=("path-to-service1-binary" "path-to-service2-binary")
DAEMONS=("$CODAC_ROOT/bin/cos-adapter")

# # List of service/daemon names. Array size must correspond to ${#DAEMONS[@]}.
# # [REQUIRED]
# NAMES=("Name of Service 1" "Name of Service 2")
NAMES=("D1-J4-FIR COS Adapter daemon")

# # [OPTIONAL]
# ARGS=(
#       "daemon1-arguments -conf ${CONFIGURATION[0]} -log ${VARFILES[0]}"
#       "daemon2-arguments -conf ${CONFIGURATION[1]}"
#      )
ARGS=("CBS_COS=D1-J4-FIR,CBS_PSOS=D1-J4-FIR,VAR_OPREQ=FSM-EVENT,VAR_OPSTATE=FSM-STATUS")

# # Redirect service/daemon console output to a specified log file. If not
# # specified, console output is redirected to /dev/null. Array size should
# # correspond to ${#DAEMONS[@]} unless you prefer default.
# # For [A3] it also makes sense to specify 'errdump' as log file, which means
# # that stderr messages will be printed on console if application returns exit
# # code different from zero.
# # [OPTIONAL]
# LOGFILES=("path-to-service1-log-file" "path-to-service2-log-file")
LOGFILES=("$CODAC_VAR/sup/cos-adapter-d1-j4-fir.log" )

# FGMODES=(f false false )
SCREENS=("screen-pos")
PROCSERVPORTS=("3332")

###########################################################################################

. $CODAC_ROOT/bin/services/service-startup
